// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yruasjxuyjhzljizbsia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlydWFzanh1eWpoemxqaXpic2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0Mjc1NDcsImV4cCI6MjA2NDAwMzU0N30.xXG8nDxnJ5TLXyt0DlDcuoQKjPTYQgRp9IcfWEwnXP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);